portfolio/apps/core/urls.py
from django.urls import path
from .views import WorksView, WorkDetailView, InformationIndexView, TagView, IndexView, CvView, StatementView, ContactFormView, ContactResultView


app_name = 'core'
urlpatterns = [
    path('', IndexView.as_view(), name='index'),
    path('information_list/', InformationIndexView.as_view(), name='information_list'),
    path('works_list/', WorksView.as_view(), name='works_list'),
    path('tag/<str:name>', TagView.as_view(), name='work_tag'),
    path('work/<slug:slug>/',  WorkDetailView.as_view(), name='work_detail'),
    path('cv/', CvView.as_view(),name='cv_list'),
    path('statement/', StatementView.index, name='statement'),
    path('contact/', ContactFormView.as_view(), name='contact_form'),
    path('contact/result/', ContactResultView.as_view(), name='contact_result'),
]

portfolio/urls.py
from django.contrib import admin
from django.urls import include, path, re_path
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('portfolio.apps.core.urls')),
    re_path('djga/', include('google_analytics.urls')),
    path('i18n/', include('django.conf.urls.i18n')),
] 
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

portfolio/apps/core/models.py
from django.db import models
from django.utils import timezone
from django.core.validators import MaxValueValidator, MinValueValidator


class Category(models.Model):
    name = models.CharField(max_length=255)
    slug = models.SlugField(unique=True)
    timestamp = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.name

class Tag(models.Model):
    name = models.CharField(max_length=50)

    def __str__(self):
        return self.name

class Information(models.Model):
    category = models.ForeignKey(Category, on_delete=models.PROTECT)
    title = models.CharField(max_length=255)
    content = models.TextField()
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    published_at = models.DateTimeField(blank=True, null=True)
    is_public = models.BooleanField(default=False)

    class Meta:
        ordering = ['-published_at']

    def save(self, *args, **kwargs):
        if self.is_public and not self.published_at:
            self.published_at = timezone.now()
        super().save(*args, **kwargs)

    def __str__(self):
        if self.is_public == False:
            is_public_text = "(非公開)"
        else:
            is_public_text = ""
        return '%s  %s' % (self.title, is_public_text)


class Work(models.Model):
    title = models.CharField(max_length=200)
    slug = models.SlugField(unique=True)
    production_year = models.IntegerField(
        validators=[MinValueValidator(2000), MaxValueValidator(2999)])
    content = models.TextField()
    used_tools = models.TextField()
    video_slug = models.SlugField(blank=True, null=True)
    thumbnail_1 = models.ImageField(upload_to='work_detail', blank=True, null=True)
    thumbnail_2 = models.ImageField(upload_to='work_detail', blank=True, null=True)
    thumbnail_3 = models.ImageField(upload_to='work_detail', blank=True, null=True)
    tag = models.ManyToManyField(Tag, blank=True)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    published_at = models.DateTimeField(blank=True, null=True)
    is_public = models.BooleanField(default=False)

    def save(self, *args, **kwargs):
        if self.is_public and not self.published_at:
            self.published_at = timezone.now()
        super().save(*args, **kwargs)

    def __str__(self):
        if self.is_public == False:
            is_public_text = "(非公開)"
        else:
            is_public_text = ""
        return '%s  %s' % (self.title, is_public_text)


class Cv(models.Model):

    class Genre(models.TextChoices):
        A_GROUP_EXHIBITION = 'Group Exhibition',
        B_SOLO_EXHIBITION = 'Solo Exhibition',
        C_BOOK = 'Books',
        D_APP = 'Apps etc.',
        E_AWARD = 'Award etc.',

    title = models.CharField(max_length=200)
    start_at = models.DateTimeField()
    end_at = models.DateTimeField(blank=True, null=True)
    place = models.CharField(max_length=200, blank=True, null=True)
    link_url = models.URLField(blank=True, null=True)
    genre = models.CharField(
        max_length=20, choices=Genre.choices, default=Genre.A_GROUP_EXHIBITION)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    published_at = models.DateTimeField(blank=True, null=True)
    is_public = models.BooleanField(default=False)

    def save(self, *args, **kwargs):
        if self.is_public and not self.published_at:
            self.published_at = timezone.now()
        super().save(*args, **kwargs)

    def __str__(self):
        if self.is_public == False:
            is_public_text = "(非公開)"
        else:
            is_public_text = ""
        return '%s  %s' % (self.title, is_public_text)

portfolio/apps/core/forms.py
from django import forms
from django.conf import settings
from django.core.mail import BadHeaderError, send_mail
from django.http import HttpResponse
from captcha.fields import ReCaptchaField

class ContactForm(forms.Form):
    name = forms.CharField(
        label='',
        max_length=100,
        widget=forms.TextInput(attrs={
            'class': 'form-control',
            'placeholder': " Name",
        }),
    )
    email = forms.EmailField(
        label='',
        widget=forms.EmailInput(attrs={
            'class': 'form-control',
            'placeholder': " Email",
        }),
    )
    message = forms.CharField(
        label='',
        widget=forms.Textarea(attrs={
            'class': 'form-control',
            'placeholder': " Message",
        }),
    )
    captcha = ReCaptchaField()

    def send_email(self):
        subject = "お問い合わせ"
        name = self.cleaned_data['name']
        email = self.cleaned_data['email']
        tmpmsg = self.cleaned_data['message']
        message = '{tmpmsg} \n\n[FROM: {name} <{email}>]'.format(tmpmsg=tmpmsg, name=name, email=email)
        from_email = '{name} <{email}>'.format(name=name, email=email)
        recipient_list = [settings.EMAIL_HOST_USER]  # 受信者リスト
        try:
            send_mail(subject, message, from_email, recipient_list)
        except BadHeaderError:
            return HttpResponse("無効なヘッダが検出されました。")

portfolio/apps/core/views.py
from django.shortcuts import render
from django.http import HttpResponse, Http404
from django.template import loader
from django.views.generic.detail import DetailView
from django.views.generic.list import ListView
from django.views.generic import TemplateView
from django.views.generic.edit import FormView
from django.urls import reverse_lazy
from django.utils import translation

from .forms import ContactForm
from .models import Information, Work, Cv, Tag

class IndexView(ListView):
    model = Work
    template_name = 'core/index.html'
    queryset = Work.objects.filter(is_public=True).order_by('-production_year', '-published_at')[:4]

    def get_context_data(self, *args, **kwargs):
        context = super(IndexView, self).get_context_data(*args, **kwargs)
        context['information_list'] = Information.objects.filter(is_public=True).order_by('-published_at')[:4]
        return context

class WorksView(ListView):
    model = Work
    template_name = 'core/works_list.html'
    queryset = Work.objects.filter(is_public=True).order_by('-production_year', '-published_at')
    paginate_by = 8

    def get_context_data(self, *args, **kwargs):
        context = super().get_context_data(*args, **kwargs)
        context['tag_list'] = Tag.objects.all
        return context

class WorkDetailView(DetailView):
    model = Work

    def get_object(self, queryset=None):
        obj = super().get_object(queryset=queryset)
        if not obj.is_public:
            raise Http404
        return obj

class TagView(ListView):
    model = Tag
    template_name = 'core/works_list.html'

    def get_context_data(self, *args, **kwargs):
        context = super().get_context_data(*args, **kwargs)
        context['filtered_works'] = Work.objects.filter(tag__name=self.kwargs.get('name'), is_public=True).order_by('-production_year', '-published_at')
        return context

    def get_queryset(self):
        return Tag.objects.filter(name=self.kwargs.get('name'))

class InformationIndexView(ListView):
    model = Information
    template_name = 'core/information_list.html'
    paginate_by = 5

    def get_queryset(self):
        return super().get_queryset().filter(is_public=True).order_by('-published_at')

class CvView(ListView):
    model = Cv
    template_name = "core/cv.html"

    def get_queryset(self):
        qs = super().get_queryset().filter(is_public=True).order_by('start_at')
        order = ['Group Exhibition', 'Solo Exhibition', 'Books', 'Apps etc.', 'Award etc.']
        return sorted(qs, key=lambda x: order.index(x.genre))

class StatementView():
    def index(request):
        return render(request, 'core/statement.html')

class ContactFormView(FormView):
    template_name = 'core/contact_form.html'
    form_class = ContactForm
    success_url = reverse_lazy('core:contact_result')

    def form_valid(self, form):
        form.send_email()
        return super().form_valid(form)

class ContactResultView(TemplateView):
    template_name = 'core/contact_result.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        current_lng = translation.get_language()
        
        success_text = "お問い合わせは正常に送信されました。" if current_lng == 'ja' else 'Your message has been sent.'
        context['success'] = success_text
        return context

portfolio/apps/core/templates/core/contact_form.html
{% extends "base.html" %}
{% load i18n %}
{% block content %}
<section id="contact_form">
  <div class="section-container">
  <div class="container">
    <div class="row">
      <div class="col-md-8">
        <h1>Contact</h1>
        <form method="POST">{% csrf_token %}
          {{ form.as_p }}
       <div class="flex-container">
          <button type="submit" class="btn-link  stitch-button">
            <div>
              <span>{% trans "送信" %}</span>
            </div>
          </button>
        </div>
        </form>
      </div>
    </div>
  </div>
  </div>
</section>
{% endblock %}

portfolio/apps/core/templates/core/contact_result.html
{% extends "base.html" %}
{% load i18n %}
{% block content %}
<section id="contact_result">
<div class="section-container">
    <div>
        {{ success }}
    </div>
    <div class="flex-container">
        <a href="/" class="stitch-button">
            <div>
                <span>{% trans "ホームに戻る" %}</span>
            </div>
        </a>
    </div>
    </div>
</section>

{% endblock %}

portfolio/apps/core/templates/core/cv.html
{% extends 'base.html' %}
{% load i18n %}
{% block content %}
<section id="cv_list">
    <div class="section-container">
    <h1>{% trans "過去の活動" %}</h1>
    {% regroup object_list by genre as cv_list %}
    <ul>
        {% for genre in cv_list %}
            <li class="cv_list_li">
            <div>
            <h2>{{ genre.grouper }}</h2>
            {% comment %} <h3>{{ genre.grouper }}</h3> {% endcomment %}
            </div>
            {% regroup genre.list by start_at|date:"Y" as objects_by_day %}
            <div>
                <ul>
                    {% for d in objects_by_day %}
                    <h3>{{ d.grouper }}</h3>
                    {% comment %} <h5>{{ d.grouper }}</h5> {% endcomment %}
                        {% for item in d.list %}
                            {% if genre.grouper == "Group Exhibition" %}
                                {% if item.link_url %}
                                    <h5 class="cv-title">{% autoescape off %}<a href="{{ item.link_url }}">{{ item.title }}</a> {% endautoescape %}</h5>
                                {% else %}
                                    <h5 class="cv-title">{{ item.title }}</h5>
                                {% endif %}
                                <div class="cv_exhibition_info">
                                    <div> 
                                        <li><small>{{ item.place }}</small></li>
                                    </div>
                                    <div class="cv_date">
                                        {% if item.end_at %}
                                            <li><small>({{ item.start_at|date:"n/j" }}</small></li>
                                            <li><small>-{{ item.end_at|date:"n/j" }})</small></li>
                                        {% else %}
                                            <li><small>({{ item.start_at|date:"n/j" }})</small></li>
                                        {% endif %}
                                    </div>
                                </div>
                            {% elif genre.grouper == "Solo Exhibition"  %}                       
                                {% if item.link_url %}
                                    <h5 class="cv-title">{% autoescape off %}<a href="{{ item.link_url }}">{{ item.title }}</a> {% endautoescape %}</h5>
                                {% else %}
                                    <h5 class="cv-title">{{ item.title }}</h5>
                                {% endif %}
                                <div class="cv_exhibition_info">
                                    <div> 
                                        <li><small>{{ item.place }}</small></li>
                                    </div>
                                    <div class="cv_date">
                                        {% if item.end_at %}
                                            <li><small>({{ item.start_at|date:"n/j" }}</small></li>
                                            <li><small>-{{ item.end_at|date:"n/j" }})</small></li>
                                        {% else %}
                                            <li><small>({{ item.start_at|date:"n/j" }})</small></li>
                                        {% endif %}
                                    </div>
                                </div>
                            {% elif genre.grouper == "Books" %}
                                <div>
                                    <h5 class="cv-title">{% autoescape off %}<a href="{{ item.link_url }}">{{ item.title }}</a> {% endautoescape %}</h5>
                                </div>
                            {% elif genre.grouper == "Apps etc." %}
        
                                <h5 class="cv-title"> {% autoescape off %}<a href="{{ item.link_url }}">{{ item.title }}</a> {% endautoescape %}</h5>
                            {% elif genre.grouper == "Award etc." %}
                                {% if item.link_url %}
                                    <h5 class="cv-title">{% autoescape off %}<a href="{{ item.link_url }}">{{ item.title }}</a> {% endautoescape %}</h5>
                                {% else %}
                                    <h5 class="cv-title">{{ item.title }}</h5>
                                {% endif %}
                            {% endif %}
                        {% endfor %}
                    {% endfor %}
                </ul>  
            </div>
            </li>
            <hr>
        {% endfor %}
    </ul>
    </div>
</section>
{% endblock %}

portfolio/apps/core/templates/core/index.html
{% extends 'base.html' %}
{% load i18n %}
{% block content %}

  <section id="top">
  </section>
  <!-- <section id="information">
    <div class="section-container">
    <h1>NEWS</h1>
    <ul class="index_information_ul">
      {% for information in information_list %}
        <li>
          <div>{{ information.published_at|date:"Y-m-d" }}</div>
          <div>{{ information.title }}</div> 
        </li>
      {% endfor %}
    </ul>
    <div class="more-button-div">
      <a href="information_list" class="more-button">
        <div>
          <span>More...</span>
        </div>
      </a>
    </div>
    </div>
  </section> -->
  <section id="works">
    <div class="section-container">
    <h1>Works</h1>
      <ul class="works_ul">
    {% for work in object_list %}
        <li>
          <a href="work/{{ work.slug }}">
            <img class="work-img" src="media/{{ work.thumbnail_1 }}" width="100%"/>
            <div class="works_caption">
              <div>
                <h5>{{ work.title }}</h5> 
                <small>({{ work.production_year }})</small> 
              </div>
            </div>
          </a>
        </li>
      {% endfor %}
      </ul>
      <div class="more-button-div">
      <a href="works_list" class="more-button">
        <div>
          <span>More...</span>
        </div>
      </a>
    </div>
    </div>
  </section>
  <section id="profile">
    <div class="section-container">
    <hr>
    <h1>Profile</h1>
    <div class="profile-name">
      <h3>{% trans "清重 影織" %}</h3><div>{% trans "きよしげ かげおり" %}</div>
    </div>
    <br>
    <p>{% trans "1992年東京生まれ。" %}<br>{% trans "東京大学教養学部卒業。" %}</p>
    <p>{% trans "大学図書館に2年間勤めた後、未経験からバックエンドエンジニアに転向。" %}<br>{% trans "さらに2年後に独立し、現在は" %}<br><br><i>{% trans "空想と現実を行き来するアーティスト" %}<br>{% trans "心の安全基地を作り、魂の望む自己表現へと導くガイド" %}</i><br><br>{% trans "として、制作・コーチングをしながら精力的に活動中。" %}</p>  
      <p>
        Twitter : <a href="https://twitter.com/kageori_ar">@kageori_ar</a><br>
        Instagram : <a href="https://www.instagram.com/kageori_ar/">@kageori_ar</a><br>
        Facebook : <a href="https://www.facebook.com/kageori.ar">{% trans "清重影織" %}</a><br>
    <div class="flex-container">
      <a href="statement" class="stitch-button">
        <div class="">
          <span>{% trans "ステートメント" %}</span>
        </div>
      </a>
    </div>
    <div class="flex-container">
      <a href="cv" class="stitch-button">
        <div class="">
          {% trans "過去の活動" %}
        </div>
      </a>
    </div>
    <div class="flex-container">
      <a href="https://www.kageori.com/" class="stitch-button">
        <div class="">
          <span>{% trans "ブログ 「影織文庫」" %}</span>
        </div>
      </a>
    </div>
   </div> 
  </section>
  <section id="contact">
  <div class="section-container">
    <hr>
    <h1>Contact</h1>
    <div class="flex-container">
    <p>{% trans "お気軽にお問い合わせください。" %}</p> 
    </div>
     <div class="flex-container">
      <a href="contact" class="stitch-button">
        <div class="">
          <span>{% trans "お問い合わせフォーム" %}</span>
        </div>
      </a>
    </div>
    </div>  
  </section>
{% endblock %}

portfolio/apps/core/templates/core/information_list.html
{% extends 'base.html' %}

{% block content %}
<section id="information-list">
  <div class="section-container">
  <h1>NEWS</h1>
  <ul>
    {% for information in object_list %}
    <li class="information-list">
      <div class="accbox">
        <div class="date-and-category">
          <div class="info-date">{{ information.published_at|date:"Y-m-d" }}</div>
          <div>{{ information.category }}</div>
        </div>  
        <input type="checkbox" id="accordion_{{ forloop.counter }}" class="cssacc" />
        <label for="accordion_{{ forloop.counter }}">{{ information.title }}</label>
        <div class="accshow">
        {% autoescape off %}
          {{ information.content | linebreaks }}
        {% endautoescape %}
        </div>
      </div>
    </li>
    {% empty %}
    <li>まだ投稿はありません。</li>
    {% endfor %}
  </ul>

  {% if is_paginated %}
  <nav>
    {% if page_obj.has_previous %}
    <a href="?page={{ page_obj.previous_page_number }}"><</a>
    {% endif %}

    {% for num in paginator.page_range %}
    {% if page_obj.number == num %}
    <span>{{ num }}</span>
    {% else %}
    <a href="?page={{ num }}">{{ num }}</a>
    {% endif %}
    {% endfor %}

    {% if page_obj.has_next %}
    <a href="?page={{ page_obj.next_page_number }}">></a>
    {% endif %}
  </nav>
  {% endif %}
  </div>
</section>  
{% endblock %}

portfolio/apps/core/templates/core/statement.html
{% extends 'base.html' %}
{% load i18n %}
{% block content %}
    <section>
    <div class="section-container">
        <h1>{% trans "ステートメント" %}</h1>
                
        <h3>{% trans "物語を届け、世界を照らす" %}</h3>
        <p>{% trans "色を塗り重ねていく絵画と異なり、切り絵は一枚の紙を切り抜いて表現する<b>「引き算の芸術」</b>である。それを用いて、雑多な世界の中から一つの物語を切り出すことを試みている。" %}</p>
        <p>{% trans "さらに、<b>ARやVR技術</b>を用い、物語を実際に目で見たり触れたりしながら、より深く楽しめるように意図している。<br>" %}</p>
        <p>{% trans "こうした表現媒体を用い、心をテーマにした童話作品と切り絵を組み合わせた「切絵童話」を紡ぎ、読み手の心を暖め、前向きに生きる希望を抱けるような作品を作っている。<br>" %}</p>
        <p>{% trans "また、歴史資料の持つストーリーや偉人の逸話などを、AR技術を用いて楽しみながら分かりやすく学べる作品を生み出し、知的好奇心を満たす喜びや楽しさを伝えている。<br><br>" %}</p>

        <h3>{% trans "誰もが安心して自由に自己表現できるように導く" %}</h3>
        <p>{% trans "素敵なアイデアを自由に思い描くのは、心の仕事。<br>それを現実化するために具体的に段取りを考えるのは、頭の仕事。<br>" %}</p>
        <p>{% trans "<b>そのままの自分で表現するための自由な心のあり方</b>と、<b>描いたアイデアを自由に具現化する技術やノウハウ</b>の両面を伝えることで、自分と同じく表現者として生きようとする人をサポートする。" %}</p>    
</div>
</section>
{% endblock %}

portfolio/apps/core/templates/core/work_detail.html
{% extends 'base.html' %}

{% block content %}

  <section id="work_detail">
    <div class="section-container">
    <h1>Works</h1>
    {% if work.video_slug %}
    <div class="iframe-video">
      <iframe width="560" height="315" src="https://www.youtube.com/embed/{{ work.video_slug }}?wmode=transparent" frameborder="0" allow="accelerometer; autoplay; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>
    </div>
    {% else %}
     <img class="work_main_image" src="{{ work.thumbnail_1.url }}" />    
    {% endif %}

    <div class="works_caption">
        <div>
          <h3>{% autoescape off %}{{ work.title }}{% endautoescape %}</h3>
          <p>({{ work.production_year }})</p>
        </div>
    </div>
    <p> {% autoescape off %}
      {{ work.content | linebreaks }} 
       {% endautoescape %}</p>
    <hr>
    <h4>使用言語・ツール</h4>
    <div class="used-tools">
      <p>{{ work.used_tools | linebreaks }}</p>
    </div> 
    <div class="work_detail-container">
    {% if work.thumbnail_1 and work.video_slug %}
    <img class="work_sub_image" src="{{ work.thumbnail_1.url }}" />
    {% endif %}
    {% if work.thumbnail_2 %}
    <img class="work_sub_image" src="{{ work.thumbnail_2.url }}"/>
    {% endif %}
    {% if work.thumbnail_3 %}
    <img class="work_sub_image" src="{{ work.thumbnail_3.url }}"  />
    {% endif %}
    </div>
      <div class="flex-container">
          <a href="/works_list" class="stitch-button">
          <div class="">
              <span>一覧に戻る</span>
          </div>
          </a>
      </div>
    </div> 
  </section>

{% endblock %}

portfolio/apps/core/templates/core/works_list.html
{% extends 'base.html' %}

{% block content %}
<section>
  <div class="section-container">
  <h1>Works</h1>
  <h5>Tags</h5>
  <div class="work_tag_column tags_list">
    {% for tag in tag_list.all %}  
    <a href="{% url 'core:work_tag' tag.name %}"><div class="work_tag">{{ tag.name }}</div></a>
    {% endfor %}
  </div>
    <ul class="works_ul">
      {% if filtered_works %}
        {% for work in filtered_works %}
        <li>
            <div class="work_tag_column">
              {% for tag in work.tag.all %}  
              <div class="work_tag">{{ tag.name }}</div>
              {% endfor %}
            </div>
            <a href="../work/{{ work.slug }}">
            <img class="work-img" src="/media/{{ work.thumbnail_1 }}"  width="100%"/>
            <div class="works_caption">
              <div>
                <h5>{% autoescape off %}{{ work.title }}{% endautoescape %}</h5> 
                <small>({{ work.production_year }})</small> 
              </div>
            </div>
          </a>
        </li>
        {% empty %}
        <li>まだ投稿はありません。</li>
        {% endfor %}
      {% else %}
        {% for work in object_list %}
          <li>
              <div class="work_tag_column">
                {% for tag in work.tag.all %}  
                <div class="work_tag">{{ tag.name }}</div>
                {% endfor %}
              </div>
              <a href="../work/{{ work.slug }}">
              <img class="work-img" src="/media/{{ work.thumbnail_1 }}"  width="100%"/>
              <div class="works_caption">
                <div>
                  <h5>{% autoescape off %}{{ work.title }}{% endautoescape %}</h5> 
                  <small>({{ work.production_year }})</small> 
                </div>
              </div>
            </a>
          </li>
        {% empty %}
        <li>まだ投稿はありません。</li>
        {% endfor %}
      </ul>
      {% endif %}

  {% if is_paginated %}
  <nav>
    {% if page_obj.has_previous %}
    <a href="?page={{ page_obj.previous_page_number }}"><</a>
    {% endif %}

    {% for num in paginator.page_range %}
    {% if page_obj.number == num %}
    <span>{{ num }}</span>
    {% else %}
    <a href="?page={{ num }}">{{ num }}</a>
    {% endif %}
    {% endfor %}

    {% if page_obj.has_next %}
    <a href="?page={{ page_obj.next_page_number }}">></a>
    {% endif %}
  </nav>
  {% endif %}
  </div>
</section>  
{% endblock %}